### ISSUE TITLE
Variables not set

### ISSUE THREAD

**Issue by brandontamm** [arvatoSCM/dockerize-magento2#3]
I cloned the repo and ran the installer - no modifications. I am getting this:
WARNING: The DATABASE_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_USER variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_NAME variable is not set. Defaulting to a blank string.

The env variables are there - not sure why it isn't reading them?

**Comment by ninnemana** [comment]
@brandontamm what did you do to solve this?

**Comment by brandontamm** [comment]
I honestly can't remember but I'll be working on this project again starting in Jan. If I run into this issue again, I'll document it here.

**Comment by brandontamm** [comment]
I suppose make sure to edit config/env.sh and run composer installation for both magento and for this project as a dependency
