### ISSUE TITLE
SQL Import?

### ISSUE THREAD

**Issue by brandontamm** [arvatoSCM/dockerize-magento2#5]
I see that db:import is missing from Magento's CLI tool - just wondering if there is a db-deployment workaround since you included phpmyadmin? Can you share how to import? How are you accessing phpmyadmin - sequel pro with credentials?

**Comment by brandontamm** [comment]
Anyone wondering the same thing - you can access phpmyadmin at http://example.com:3306 using your env variables

**Comment by renepenner** [comment]
hey brandontamm,

you can import databases directly from comandline with docker:

`docker exec -it your_mysql_container_name mysql -u youruser -p yourpass your_databases_name < dump.sql`
