### ISSUE TITLE
Update Composer Dependencies?

### ISSUE THREAD

**Issue by brandontamm** [arvatoSCM/dockerize-magento2#6]
I have been using your Magento 1.x workflow using "./magento composer update" - can you share the equivalent to that using the Magento 2.x project? Thank you!

**Comment by andreaskoch** [comment]
You can watch the [live demo of the arvatoSCM/dockerize-magento2 project](https://www.youtube.com/watch?v=4V9Uk_XfAZM) from the recording of this years Imagine conference.
The video shows the whole process of dockerizing a Magento 2 project:

https://youtu.be/4V9Uk_XfAZM?t=30m10s

[![screen shot of the Imagine 2016 - Breakout VII - Scalable Magento Development with Containers video](https://cloud.githubusercontent.com/assets/247364/15578459/ced8ff88-2360-11e6-9ec4-1e43daf8df65.png)](https://youtu.be/4V9Uk_XfAZM?t=30m10s)

Let me know if this answers your questions.

**Comment by brandontamm** [comment]
I did watch the "Scaling Magento with Docker" presentation from Imagine 2016 - thank you for giving back to the Magento Community! This truly is a great project!

I successfully completed the installation at qa1.quickattach.com and was working on adding required modules. I wasn’t able to successfully add a module to the project. 

Here is a link to a pastebin of my attempts:
    http://pastebin.com/b1U6shxZ

Here was the workflow I was trying to follow:
    composer require ebizmarts/magento2-magemonkey
    bin/console exec module:enable ebizmarts/magento2-magemonkey
    bin/console exec setup:upgrade

Can you point out where I am going wrong and how to do add modules the right way? Thank you Andy!

**Comment by brandontamm** [comment]
Would you recommend adding a composer installation to the build of the php dockerfile and php dependencies that Magento CLI is looking for? It seems that these missing components are the reasons for the errors....Or is there a different workflow that I should be using for adding extensions/modules?

**Comment by ariefbudiyono** [comment]
@brandontamm did you success add your new module?

@andreaskoch thanks for your great magento2 docker project, i already install it on my os x, follow your instruction. can u make next tutorial how to deploy to production server, especially use docker cloud or something?

regards
